name: permit_user_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  dio: ^5.7.0
  dotted_border: ^2.1.0
  email_validator: ^3.0.0
  equatable: ^2.0.7
  file_picker: ^8.1.4
  flutter:
    sdk: flutter
  flutter_smart_dialog: ^4.9.8+5
  flutter_svg: ^2.0.14
  google_fonts: ^6.2.1
  http: ^1.2.2
  marquee: ^2.3.0
  stacked: ^3.4.0
  stacked_services: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
