#!/bin/sh
printf "\e[33;1m%s\e[0m\n" 'Pre-Commit'

# Undo the stash of the files
pop_stash_files () {
    if [ -n "$hasChanges" ]; then
        printf "\e[33;1m%s\e[0m\n" '=== Applying git stash changes ==='
        git stash pop
    fi
}

# Stash unstaged files
hasChanges=$(git diff)
if [ -n "$hasChanges" ]; then
    printf "\e[33;1m%s\e[0m\n" 'Stashing unstaged changes'
    git stash push --keep-index
fi

# Dart fix
printf "\e[33;1m%s\e[0m\n" '=== Running Dart Fix ==='
dart fix --apply
printf "\e[32;1m%s\e[0m\n" 'Finished running Dart Fix'
printf '%s\n' "${avar}"

# Flutter Analyzer
printf "\e[33;1m%s\e[0m\n" '=== Running Flutter analyzer ==='
flutter analyze
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" '=== Flutter analyzer error ==='
  pop_stash_files
  exit 1
fi
printf "\e[32;1m%s\e[0m\n" 'Finished running Flutter analyzer'
printf '%s\n' "${avar}"

# Unit tests
printf "\e[33;1m%s\e[0m\n" '=== Running Very Good Unit and Widget Tests ==='
flutter test --coverage --test-randomize-ordering-seed random
if [ $? -ne 0 ]; then
  printf "\e[31;1m%s\e[0m\n" '=== Unit tests error ==='
  pop_stash_files
  exit 1
fi
printf "\e[32;1m%s\e[0m\n" 'Finished running Very Good Unit and Widget Tests'
printf '%s\n' "${avar}"

hasNewFilesFormatted=$(git diff)
if [ -n "$hasNewFilesFormatted" ]; then
    git add .
    printf "\e[32;1m%s\e[0m\n" 'Formated files added to git stage'
fi

pop_stash_files

printf "\e[32;1m%s\e[0m\n" 'Finished running Pre-Commit'